name = "delivery-mgmt-backend"
main = "backend-hono/src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"

[[kv_namespaces]]
binding = "SESSIONS"
id = "1a0532ef0ad74209b2b50fded1ce81d4"  # Replace with actual KV namespace ID from: wrangler kv:namespace create "SESSIONS"
preview_id = "c9bfc114990f4dae94195f588aa4248c"  # Replace with preview ID from: wrangler kv:namespace create "SESSIONS" --preview

# Environment variables will be set via Cloudflare dashboard
# GOOGLE_CLIENT_ID
# GOOGLE_CLIENT_SECRET  
# GOOGLE_REDIRECT_URL
# SOLAPI_CLIENT_ID
# SOLAPI_CLIENT_SECRET
# SOLAPI_REDIRECT_URL
# FRONTEND_URL