name = "deliver-mgmt-backend"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"
GOOGLE_CLIENT_ID = "80696117268-nk74sskpu2uerfajr7enr0084tusje4g.apps.googleusercontent.com"
GOOGLE_REDIRECT_URL = "https://deliver-mgmt-backend.coreanq.workers.dev/api/auth/google/callback"
FRONTEND_URL = "https://deliver-mgmt.pages.dev"
SOLAPI_CLIENT_ID="CIDDSMB8ODYD3UOQ"
SOLAPI_REDIRECT_URL="https://deliver-mgmt-backend.coreanq.workers.dev/api/solapi/auth/callback"
SOLAPI_API_BASE_URL="https://api.solapi.com"

[[kv_namespaces]]
binding = "SESSIONS"
id = "1a0532ef0ad74209b2b50fded1ce81d4"  # Replace with actual KV namespace ID from: wrangler kv:namespace create "SESSIONS"
preview_id = "c9bfc114990f4dae94195f588aa4248c"  # Replace with preview ID from: wrangler kv:namespace create "SESSIONS" --preview

# Environment variables will be set via Cloudflare dashboard
# GOOGLE_CLIENT_ID
# GOOGLE_CLIENT_SECRET  
# GOOGLE_REDIRECT_URL
# SOLAPI_CLIENT_ID
# SOLAPI_CLIENT_SECRET
# SOLAPI_REDIRECT_URL
# FRONTEND_URL
# EMAIL_HASH_SALT  # Must be the SAME across environments (unified user key salt)
